<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Login Gagal_ndf4w-closeIcon-126</name>
   <tag></tag>
   <elementGuidId>7ca3e2c3-25d8-4973-bd01-ae6c44885270</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@type='error']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ndf4w-closeIcon-126</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2e329a8d-5808-447b-b5e8-37c6e1ba052a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ndf4w-closeIcon-126</value>
      <webElementGuid>85b06007-7608-4718-a32f-e892a9c96a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>0f5fc65b-7148-4e12-a89b-8a9a6352998f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>theme</name>
      <type>Main</type>
      <value>colored</value>
      <webElementGuid>42f2914a-7f99-4f8f-856d-9bcf86849188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appToasterContainer&quot;)/span[@class=&quot;ndf4w-closeIcon-126&quot;]</value>
      <webElementGuid>668e8713-061d-475a-86b6-8613836a83de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@type='error']</value>
      <webElementGuid>daa420ad-b1bb-4fd9-b8cb-504ce26ca45e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appToasterContainer']/span</value>
      <webElementGuid>086efce9-8afe-4807-aae5-104975a123a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>19503316-4d44-42d0-b299-a19e1e56b0b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@type = 'error']</value>
      <webElementGuid>ba0c169e-9e9d-4638-87b8-316a427d5491</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
